server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clound?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  application:
    name: payment-service


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: payment8001
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.entities